service: devsapi

frameworkVersion: '4'
org: curriculosayajinbot

provider:
  name: aws
  runtime: nodejs18.x
  
functions:
  hello:
    handler: app.handler
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /api/v1/jobs
          method: get

package:
  include:
    - node_modules/**
    - app.js

plugins:
  - serverless-offline
